name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm ci
      - run: npm run build

      - name: Set Git Identity
        run: |
          git config user.name "PolkamBharath05"
          git config user.email "mudirajbharath47@gmail.com"

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          npx gh-pages -d dist -u "PolkamBharath05<mudirajbharath47@gmail.com>" -r https://x-access-token:${GH_TOKEN}@github.com/PolkamBharath05/reactcicd.git